# This is a basic workflow to help you get started with Actions

name: CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Activate Namespace
      uses: okteto/namespace@master
      with:
        namespace: sreynoso-dev
    
    - name: Deploy App
      uses: okteto/apply@master
      with:
        namespace: sreynoso-dev
        manifest: k8s.yml
    
    - name: Push
      uses: okteto/push@master
      with:
        namespace: sreynoso-dev
     
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'
    
    - name: Verify
      uses: srt32/uptime@v0.2
      with:
        url-to-hit: "https://upc-pool-frontend-sreynoso-dev.cloud.okteto.net"
        expected-statuses: "200"
